# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03b0e4873e81ae46c6f251b38219486340e68a42bba4181a0be4ac925f8d8257fd2421d2e311a321107c92cff5b35f71aaa58cec467a7b5764b5e7365f869c4

test:
  secret_key_base: 39754ad9a4b64ea7c0b03b89f23c183414009d4139171f8aa9f73abc537cb3dc6f0741c8c323a9437dd4c67d55ccc43bc5841879f89fff9fadd823f9cd570d40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
